brew "autoconf"
brew "automake"
brew "cmake"
brew "heroku"
brew "pv"
brew "pyenv"
brew "tmux"
brew "wget"
cask "xquartz"
brew "wine"
brew "zsh"
brew "zsh-completions"

cask "dropbox"
cask "vlc"
cask "the-unarchiver"
cask "visual-studio-code"