#!/usr/bin/env bash

# source bash profile to get environment variables set
[ -f "$HOME/.bash_profile" ] && source "$HOME/.bash_profile"

if ! dscl . -read "$HOME" UserShell | grep -q -E "zsh"; then
  # set default shell to zsh
  chsh -s /bin/zsh $USER
fi

if [ -z "$USER_PROFILE_LOADED"] && [ -f "$HOME/.bash_profile" ]; then
  source "$HOME/.bash_profile"
fi
# tell the script to exit with failure if any command
# returns a non-zero exit code
set -e

DOTFILESDIRREL=$(dirname $0)
cd $DOTFILESDIRREL/..
USER_DOTFILES=$(pwd -P)

#---------------------------------------------------------------------
# Projects.  The list of supported projects comes from
# https://github.com/daptiv/dotfiles/tree/master/projects/
# Each folder name is a project.  Just include the folder name as
# outlined below, to include that project in your setup.
#---------------------------------------------------------------------
echo "Configuring projects"
SETUP_SCRIPT="$HOME/.daptiv-dotfiles/projects/setup"
if [ -f "$SETUP_SCRIPT" ]; then
  # you can comment out any project you don't wish to include by putting a # at the beginning of the line
  bash "$SETUP_SCRIPT" foxglove
  # bash "$SETUP_SCRIPT" ppm
  bash "$SETUP_SCRIPT" ppmspa
  # bash "$SETUP_SCRIPT" ttm
  bash "$SETUP_SCRIPT" pmdashboard
  # bash "$SETUP_SCRIPT" dtb
  # bash "$SETUP_SCRIPT" new-feature-popup
  # bash "$SETUP_SCRIPT" react-theme
  bash "$SETUP_SCRIPT" cognos
  echo "Finished configuring projects"
fi

# Install Daptiv Projects --------------
SETUP_SCRIPT="$HOME/.daptiv-dotfiles/projects/setup"

# TTM -----
[ -f "$SETUP_SCRIPT" ] && bash "$SETUP_SCRIPT" ttm

