#!/usr/bin/env bash

# This script is run before items in your .Brewfile are installed

DOTFILESDIRREL=$(dirname $0)
cd $DOTFILESDIRREL/..
USER_DOTFILES=$(pwd -P)

ensure_dotfile_link() {
  HOMEFILE="$HOME/$1"
  DOTFILE="$USER_DOTFILES/$1"

  if [ -L "$HOMEFILE" ] && ! [ -d "$DOTFILE" ]; then
    ln -sfv "$DOTFILE" "$HOMEFILE"
  else
    rm -rv "$HOMEFILE"
    ln -sv "$DOTFILE" "$HOMEFILE"
  fi
}

# use the ensure_dotfile_link command to link files into your home directory
ensure_dotfile_link .Brewfile
